import type { HeritageSite } from "./types";

export const MOCK_SITES: HeritageSite[] = [
  {
    id: "1",
    code: "1-1",
    name: "万里长城",
    province: "北京市",
    city: "北京市",
    district: null,
    address: "北京市延庆区",
    category: "古建筑",
    era: "春秋至明",
    batch: 1,
    batch_year: 1961,
    latitude: 40.4319,
    longitude: 116.5704,
    description: "万里长城是中国古代的军事防御工程，是世界上修建时间最长、工程量最大的一项古代防御工程。",
    wikipedia_url: "https://zh.wikipedia.org/wiki/%E4%B8%87%E9%87%8C%E9%95%BF%E5%9F%8E",
    image_url: null,
    is_open: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    code: "1-2",
    name: "故宫",
    province: "北京市",
    city: "北京市",
    district: "东城区",
    address: "北京市东城区景山前街4号",
    category: "古建筑",
    era: "明、清",
    batch: 1,
    batch_year: 1961,
    latitude: 39.9163,
    longitude: 116.3972,
    description: "北京故宫是中国明清两代的皇家宫殿，旧称紫禁城，位于北京中轴线的中心。",
    wikipedia_url: "https://zh.wikipedia.org/wiki/%E6%95%85%E5%AE%AB",
    image_url: null,
    is_open: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    code: "1-3",
    name: "周口店遗址",
    province: "北京市",
    city: "北京市",
    district: "房山区",
    address: "北京市房山区周口店镇",
    category: "古遗址",
    era: "旧石器时代",
    batch: 1,
    batch_year: 1961,
    latitude: 39.6894,
    longitude: 115.9311,
    description: "周口店遗址是中国旧石器时代的重要遗址，北京猿人的发现地。",
    wikipedia_url: null,
    image_url: null,
    is_open: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    code: "1-81",
    name: "殷墟",
    province: "河南省",
    city: "安阳市",
    district: null,
    address: "河南省安阳市殷都区",
    category: "古遗址",
    era: "商",
    batch: 1,
    batch_year: 1961,
    latitude: 36.1275,
    longitude: 114.3053,
    description: "殷墟是中国商代晚期的都城遗址，是中国历史上第一个有文献可考并为考古学和甲骨文所证实的都城遗址。",
    wikipedia_url: null,
    image_url: null,
    is_open: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    code: "1-82",
    name: "郑州商代遗址",
    province: "河南省",
    city: "郑州市",
    district: null,
    address: "河南省郑州市管城回族区",
    category: "古遗址",
    era: "商",
    batch: 1,
    batch_year: 1961,
    latitude: 34.7533,
    longitude: 113.6767,
    description: "郑州商代遗址即郑州商城遗址，是商代早中期的都城遗址。",
    wikipedia_url: null,
    image_url: null,
    is_open: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    code: "1-83",
    name: "龙门石窟",
    province: "河南省",
    city: "洛阳市",
    district: null,
    address: "河南省洛阳市洛龙区龙门镇",
    category: "石窟寺及石刻",
    era: "北魏至唐",
    batch: 1,
    batch_year: 1961,
    latitude: 34.5655,
    longitude: 112.4713,
    description: "龙门石窟位于洛阳市南郊伊河两岸的龙门山与香山上，是世界上造像最多、规模最大的石刻艺术宝库。",
    wikipedia_url: null,
    image_url: null,
    is_open: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "7",
    code: "3-248",
    name: "白马寺",
    province: "河南省",
    city: "洛阳市",
    district: null,
    address: "河南省洛阳市洛龙区白马寺镇",
    category: "古建筑",
    era: "东汉至清",
    batch: 3,
    batch_year: 1988,
    latitude: 34.7317,
    longitude: 112.5850,
    description: "白马寺是佛教传入中国后兴建的第一座官办寺院，被尊为中国佛教的「祖庭」和「释源」。",
    wikipedia_url: null,
    image_url: null,
    is_open: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "8",
    code: "4-220",
    name: "嵩岳寺塔",
    province: "河南省",
    city: "郑州市",
    district: "登封市",
    address: "河南省郑州市登封市嵩山南麓",
    category: "古建筑",
    era: "北魏",
    batch: 1,
    batch_year: 1961,
    latitude: 34.4608,
    longitude: 113.0650,
    description: "嵩岳寺塔是中国现存最古老的砖塔，也是世界上最早的筒体建筑。",
    wikipedia_url: null,
    image_url: null,
    is_open: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "9",
    code: "5-450",
    name: "明十三陵",
    province: "北京市",
    city: "北京市",
    district: "昌平区",
    address: "北京市昌平区十三陵镇",
    category: "古墓葬",
    era: "明",
    batch: 1,
    batch_year: 1961,
    latitude: 40.2530,
    longitude: 116.2271,
    description: "明十三陵是明朝十三位皇帝的陵墓群，是世界上保存完整的皇家陵墓群之一。",
    wikipedia_url: null,
    image_url: null,
    is_open: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "10",
    code: "6-887",
    name: "中国人民抗日战争纪念馆",
    province: "北京市",
    city: "北京市",
    district: "丰台区",
    address: "北京市丰台区卢沟桥城南街77号",
    category: "近现代重要史迹及代表性建筑",
    era: "1937年",
    batch: 6,
    batch_year: 2006,
    latitude: 39.8535,
    longitude: 116.2157,
    description: "中国人民抗日战争纪念馆是全国唯一一座全面反映中国人民抗日战争历史的大型综合性专题纪念馆。",
    wikipedia_url: null,
    image_url: null,
    is_open: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
